info:
  contact: {}
paths:
  /clients:
    get:
      description: Returns all clients
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get all clients
swagger: "2.0"
